[build]
  publish = "public"
  command = "hugo --gc --minify"
[build.environment]
  HUGO_VERSION = "0.147.8"
  DART_SASS_VERSION = "1.89.2"
  NODE_VERSION = "22"
  GO_VERSION = "1.24.3"
  HUGO_ENV = "production"
 ## HUGO_THEME = "repo"
 ## HUGO_BASEURL = "https://anatole-demo.netlify.app"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"